server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${DB_MONGO_URI:mongodb://localhost:27017/pl_invoices}
  application:
      name: InvoiceService
      allow-origin: ${ALLOW_ORIGIN?:http://localhost:4201}
logging:
  level:
    root: info
    pl.sparkidea: warn
    com.netflix.discovery: off
security:
  default-user:
    name: ${DEFAULT_USER_NAME}
    password: ${DEFAULT_USER_PASSWORD}