#!groovy
pipeline {
    agent any

    stages {
       stage('Build') {
        steps {
            sh "./gradlew clean bootJar"
        }
       }
       stage('Results') {
        steps {
            archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
        }
       }
    }

}