#!groovy
pipeline {
    agent any

    stages {
       stage('Build') {
        sh "./gradlew clean bootJar"
       }
       stage('Results') {
          archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
       }
    }

}